In [2]:
import torch

print(torch.__version__)

1.2.0


**1. Define Tensor**

Tensor is a data structure used in PyTorch. 

Tensors are similar to NumPy’s ndarrays, with the addition being that Tensors can also be used on a GPU to accelerate computing.

![alt text](https://www.kdnuggets.com/wp-content/uploads/tensor-examples.jpg)

In [0]:
x = torch.empty(5, 3)
print(x)
print(x.shape)

tensor([[2.5636e-36, 0.0000e+00, 4.4842e-44],
        [0.0000e+00,        nan, 5.6052e-44],
        [8.4034e+20, 3.3459e+21, 5.3697e-05],
        [1.3721e-05, 5.4649e-05, 6.7651e+22],
        [6.4098e-10, 1.6765e+22, 4.6291e-01]])
torch.Size([5, 3])


In [0]:
x = torch.rand(5, 3)
print(x)

tensor([[0.8374, 0.6568, 0.9469],
        [0.5035, 0.1892, 0.6594],
        [0.1111, 0.9556, 0.1687],
        [0.3096, 0.7158, 0.5957],
        [0.0495, 0.7191, 0.4629]])


In [0]:
import numpy as np

x = np.ones((5, 3))
y = torch.from_numpy(x)

print(x)
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [0]:
x = torch.Tensor([[2,1,2],[2,3,6],[3,4,8],[9,1,2],[4,5,2]])
print(x)

tensor([[2., 1., 2.],
        [2., 3., 6.],
        [3., 4., 8.],
        [9., 1., 2.],
        [4., 5., 2.]])


In [0]:
x = torch.ones(4, 5, 6, 7)
print(x.shape)

torch.Size([4, 5, 6, 7])


**2. Index Tensor**

In [0]:
x = torch.rand(2,3,2)
print(x)

tensor([[[0.7446, 0.9678],
         [0.9088, 0.7623],
         [0.9062, 0.6040]],

        [[0.5469, 0.4662],
         [0.5433, 0.2112],
         [0.2959, 0.8491]]])


In [0]:
print(x[1])
print(x[1].shape)

tensor([[0.5469, 0.4662],
        [0.5433, 0.2112],
        [0.2959, 0.8491]])
torch.Size([3, 2])


In [0]:
print(x[-1])
print(x[-1].shape)

tensor([[0.5469, 0.4662],
        [0.5433, 0.2112],
        [0.2959, 0.8491]])
torch.Size([3, 2])


In [0]:
print(x[:,0])
print(x[:,0].shape)

tensor([[0.7446, 0.9678],
        [0.5469, 0.4662]])
torch.Size([2, 2])


In [0]:
print(x[:,1:3])
print(x[:,1:3].shape)

tensor([[[0.9088, 0.7623],
         [0.9062, 0.6040]],

        [[0.5433, 0.2112],
         [0.2959, 0.8491]]])
torch.Size([2, 2, 2])


**3. Reshape Tensor**

In [25]:
x = torch.rand(4,3,2)
print(x.shape)


print(x.view(12, 2).shape) # .view(): Returns a new tensor with the same data as the self tensor but of a different shape.
print(x.view(-1, 2).shape) # If one of the dimensions is -1, its size can be inferred
print(x.view(4, -1).shape)
print(x.view(-1).shape)

torch.Size([4, 3, 2])
torch.Size([12, 2])
torch.Size([12, 2])
torch.Size([4, 6])
torch.Size([24])


In [26]:
print(x.permute([1,0,2]).shape)
print(x.permute([2,1,0]).shape)

torch.Size([3, 4, 2])
torch.Size([2, 3, 4])


In [28]:
print(x.unsqueeze(0).shape)           # .unsqueeze(): Returns a new tensor with a dimension of size one inserted at the specified position.
print(x.unsqueeze(-1).shape)

unsqueezed_x = x.unsqueeze(-1)
print(unsqueezed_x.squeeze().shape)   # .squeeze(): Returns a tensor with all the dimensions of input of size 1 removed.

torch.Size([1, 4, 3, 2])
torch.Size([4, 3, 2, 1])
torch.Size([4, 3, 2])


**4. CUDA Extensions**

![alt text](https://2.bp.blogspot.com/-hNBj-v6c5As/WR8UefJAFkI/AAAAAAAAAis/2KXxy8EgSSE6gsLoj6dbuQZaYnWdofrcACLcB/s400/GPU_vs_CPU.png)

![alt text](https://4.bp.blogspot.com/-3I8tFgCq4Xg/WSaoo8sI9KI/AAAAAAAAAjc/wA06nUNFFus6t5tpoVmWoBXrQXwtdLQbgCLcB/s640/pytorch_cpu_v_gpu_2.png)

In [0]:
print(torch.cuda.is_available())
print(torch.cuda.device_count())

True
1


In [0]:
!nvidia-smi

Thu Oct 17 15:19:16 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 430.40       Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   46C    P0    60W / 149W |      0MiB / 11441MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU  

In [0]:
x = torch.rand(5,3)
print(x)
print(x.device)

tensor([[0.7391, 0.0859, 0.0604],
        [0.3890, 0.7486, 0.5022],
        [0.8036, 0.9152, 0.9488],
        [0.3435, 0.7254, 0.2349],
        [0.5282, 0.5450, 0.1722]])
cpu


In [0]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

x = x.to(device)
print(x)
print(x.device)

tensor([[0.7391, 0.0859, 0.0604],
        [0.3890, 0.7486, 0.5022],
        [0.8036, 0.9152, 0.9488],
        [0.3435, 0.7254, 0.2349],
        [0.5282, 0.5450, 0.1722]], device='cuda:0')
cuda:0


In [0]:
x = torch.rand(5,3)
print(x.device)

x = x.cuda()
print(x.device)

x = x.cpu()
print(x.device)

cpu
cuda:0
cpu
